### ISSUE TITLE
Will csl support multiple languages/locates in one style?

### ISSUE THREAD

**Issue by specter119** [citation-style-language/schema#133] opened 2016-06-03 14:29 UTC
Chinese GB/T 7714-2015 orders that the bibliography should display according to the language/location of each article.

* For example: 
```sh
"et al." (English) = "等." (Chinese)
"nth edition" (English) = "第n版" (Chinese)
```

will csl support control flow for languages/locates ?

**Comment by rmzelle** [comment] 2016-06-03 15:43
It's on our radar. Juris-M (a fork of Zotero for Firefox; https://juris-m.github.io/) uses a custom version of CSL that allows for this, but we haven't decided yet how to support this in standard CSL.

Closing as duplicate of https://github.com/citation-style-language/schema/issues/63.

**Closed by rmzelle** 2016-06-03 15:43 UTC

**Comment by shixuguo** [comment] 2017-12-22 17:35
@specter119 is there any csl file of GBT 7714-2015 available?

**Comment by specter119** [comment] 2017-12-23 01:23
@shixuguo no yet as I know.
